In [5]:
# 從一個陣列開始
import numpy as np
a = np.arange( 15 ).reshape( 5 , 3 )

#ndarray.dtype： 陣列中的資料型態
print( a.dtype )
#ndarray.itemsize： 陣列中每個元素佔用的空間
print( a.itemsize)

int64
8


In [10]:
#numpy 中的型態判斷
print(a.dtype == 'int64') 

#numpy 中的屬性判斷
print(a.dtype is 'int64') 
print(a.dtype is np.int64) 

print(a.dtype is np.dtype('int64'))

True
False
False
True


<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-10-6eef2c7471f2>:5: SyntaxWarning: "is" with a literal. Did you mean "=="?
  print(a.dtype is 'int64')


In [11]:
#int 代表「執行電腦中最大可表示的範圍」
print(a.dtype == 'int') 
print(a.dtype == np.int) 
print(a.dtype == np.dtype('int')) 

True
True
True


# 作業-基礎題
1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

In [17]:
print("type(...) 表示數據結構類型")
print('type(a): ', type(a))

print("ndarray.dtype 表示陣列中的資料型態")
print('a.dtype: ', a.dtype)

type(...) 表示數據結構類型
type(a):  <class 'numpy.ndarray'>
ndarray.dtype 表示陣列中的資料型態
a.dtype:  int64


2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

In [19]:
# 記得先 Import 正確的套件
import numpy as np
a = np.arange( 15 ).reshape( 5 , 3 )
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
def is_dtype(a, t):
    return a.dtype == t 

In [23]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) 

# 測試二
print(is_dtype(a, np.int))

# 測試三
print(is_dtype(a, np.dtype('int'))) 

True
True
True


3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

In [27]:
def is_dtype(a, t):
    return a.dtype is t

a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) 

# 測試二
print(is_dtype(a, np.int))

# 測試三
print(is_dtype(a, np.dtype('int'))) 


print("使用 is 的話就必須要跟 np.dtype 物件來相比")

False
False
True
使用 is 的話就必須要跟 np.dtype 物件來相比


In [32]:
def is_dtype(a, t):
    return type(a) == np.dtype(t)

a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) 

# 測試二
print(is_dtype(a, np.int))

# 測試三
print(is_dtype(a, np.dtype('int'))) 

print("type表示數據結構類型")

False
False
False
type表示數據結構類型


In [33]:
def is_dtype(a, t):
    return type(a) is np.dtype(t)

a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) 

# 測試二
print(is_dtype(a, np.int))

# 測試三
print(is_dtype(a, np.dtype('int'))) 

print("type表示數據結構類型")

False
False
False
type表示數據結構類型


# 作業-進階題

1. 將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

In [44]:
array1 = np.array(range(30))
print( array1)

array1.reshape( ( 5, 6 ), order = 'F' ) #以列的順序儲存資料

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

2. 呈上題的 array，找出被 6 除餘 1 的數的索引

In [51]:
array1[array1%6==1]

array([ 1,  7, 13, 19, 25])