# 認識 Numpy 套件與 Array 陣列定義

正確使用 Array 的常用屬性，能夠掌握 Array 的重要特性

In [18]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)


<module 'numpy' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>
1.18.5


In [19]:
# 從一個陣列開始
import numpy as np
a = np.arange( 15 ).reshape( 5 , 3 )
print( a ) # 利用 print(...) 印出陣列

print( type( a ) )

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
<class 'numpy.ndarray'>


In [20]:
# 陣列的常用屬性
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.data)

2
(5, 3)
15
int64


In [22]:
# List 與 Array 的轉換
list( a )

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

In [16]:
a.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11], [12, 13, 14]]

# 作業-基礎題

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

In [47]:
import numpy as np
a = np.arange( 60 ).reshape( 2,  5 , 6 )
print( "範例陣列\n", 
      a )

print('\n list()只轉換第一階的資料\n ', list(a))
print('\n 但是 tolist()轉換全部的資料\n: ', a.tolist())

範例陣列
 [[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]]

 list()只轉換第一階的資料
  [array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]]), array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])]

 但是 tolist()轉換全部的資料
:  [[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]], [[30, 31, 32, 33, 34, 35], [36, 37, 38, 39, 40, 41], [42, 43, 44, 45, 46, 47], [48, 49, 50, 51, 52, 53], [54, 55, 56, 57, 58, 59]]]


2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）


In [49]:
# 記得先 Import 正確的套件

a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

In [55]:
print("a = np.random.randint(10, size=6) \n")

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a))

a = np.random.randint(10, size=6) 

[5 2 4 4 3 4]
1
(6,)
6
int64
8
6
<class 'numpy.ndarray'>


In [56]:
print( "b = np.random.randint(10, size=(3,4)) \n")

print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b))

b = np.random.randint(10, size=(3,4)) 

[[0 0 2 6]
 [7 6 6 6]
 [0 1 1 4]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [57]:
print(" c = np.random.randint(10, size=(2,3,2)) \n")

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c))

 c = np.random.randint(10, size=(2,3,2)) 

[[[6 9]
  [1 0]
  [1 5]]

 [[2 2]
  [3 6]
  [7 0]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。

In [59]:
a = np.random.randint(10, size=6) 

print( a.tolist( ))
print( list( a ))

[8, 0, 0, 1, 9, 3]
[8, 0, 0, 1, 9, 3]


In [60]:
b = np.random.randint(10, size=(3,4)) 

print( b.tolist( ))
print( list( b ))

[[2, 9, 6, 3], [9, 1, 2, 6], [4, 6, 0, 7]]
[array([2, 9, 6, 3]), array([9, 1, 2, 6]), array([4, 6, 0, 7])]


In [61]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))

[[[5, 3], [8, 4], [1, 8]], [[0, 8], [8, 1], [5, 4]]]
[array([[5, 3],
       [8, 4],
       [1, 8]]), array([[0, 8],
       [8, 1],
       [5, 4]])]


In [64]:
def tolist(iterable):
    return iterable.tolist()

print(tolist(a))
print(tolist(b))
print(tolist(c))

[8, 0, 0, 1, 9, 3]
[[2, 9, 6, 3], [9, 1, 2, 6], [4, 6, 0, 7]]
[[[5, 3], [8, 4], [1, 8]], [[0, 8], [8, 1], [5, 4]]]


# 作業-延伸題:
在array中，可以靈活應用索引幫助資料擷取
作業重點:
陣列的索引、切片、以及屬性，皆需要注意使用方式
陣列之中索引式由0開始請同學注意


1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [68]:
import numpy as np

a = np.arange( 0, 21, 1 )

print("首數為0，尾數為20，公差為1的等差數列 \n", a )

首數為0，尾數為20，公差為1的等差數列 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


2.呈上題，將以上數列取出偶數。

In [72]:
b = np.arange( 0, 21, 2 )

print("首數為0，尾數為20，公差為1的等差數列取出偶數 \n", b )

首數為0，尾數為20，公差為1的等差數列取出偶數 
 [ 0  2  4  6  8 10 12 14 16 18 20]


3.呈1題，將數列取出3的倍數。

In [71]:
c = np.arange( 0, 21, 3 )

print("首數為0，尾數為20，公差為1的等差數列中3的倍數 \n", c )

首數為0，尾數為20，公差為1的等差數列中3的倍數 
 [ 0  3  6  9 12 15 18]
